### ISSUE TITLE
Password management: Replace DPAPI with Credential Store (a.k.a. Vault)

### ISSUE THREAD

**Issue by hershi** [Microsoft/mail2bug#1]
Current way of storing passwords for logging in to email/TFS is by encrypting them with DPAPI and saving to a file. 
The windows credential store is a more appropriate infrastructure for managing such credentials, and switching from one to the other would be mostly straightforward. As part of this change, retrieval of the password should be moved into the Config classes, such that the consumers won't care about how the credentials are protected

**Comment by jeffwilcox** [comment]
An ask, if anyone tackles this, is to envision cloud scenarios, too, at least while identifying the secrets resolution process in the config - reading and processing the configuration might be an asynchronous operation.

I have a cloud instance of _mail2bug_ running now that uses Azure AD and Azure KeyVault to grab account secrets at runtime using the application's identity - but it feels like a kludge how I had to add it into multiple places wherever the DPAPI decrypt calls happen for now.

**Comment by hershi** [comment]
Thanks for the PR Jeff
I agree that the code can be cleaned up a bit to avoid having to make the change in multiple points, but your PR is generally pretty clean, so I think it solves this issue
