### ISSUE TITLE
Recommendation for appropriate ConversationID for Scrum Process Template

### ISSUE THREAD

**Issue by 3imuhanerd** [microsoft/mail2bug#107]
Hello,

I am using Scrum Process Template for my project, which is being hosten on Azure DevOps Server 2019. I don't want to define a new custom field for the ConversationID. Which Filed would you recommend to use as a ConversationID? 

I don't want to use a field that could be overwritten from the system.

Thank you very much!

**Comment by 3imuhanerd** [comment]
@jeffwilcox you have used "Integration Build" for this in your blog (https://www.jeff.wilcox.name/2017/02/mail2bug/). Is it safe to use this field as a ConversationID?

**Comment by jeffwilcox** [comment]
I felt so, but it's up to your project and how manage the work items. It was a field I did not see being used at all in my devops project.
