### ISSUE TITLE
Mail2Bug does not store ongoing conversations for next scheduled task

### ISSUE THREAD

**Issue by mocdaniel** [microsoft/mail2bug#113]
We are currently facing a weird issue with Mail2Bug where seemingly everything is working fine, incoming emails are recognized and created as work items in TFS, answers to preexisting conversations are appended to existing TFS-Items, images and documents are attached correctly etc.

Anyways, this is only working within a running instance of the service, e.g. when starting it via console and running it permanently, the described behaviour can be monitored. Once we try running the service as a scheduled task, incoming answers to preexisting conversations are duplicated as new work items **if** the original email was processed in an 'ancestor' instance of the scheduled task.

Did we miss anything during the setup stage or can this be considered as a bug? 

Our scheduled task is configured as suggested in the basic setup documentation, we run 180 iterations in a 1s interval for each task instance.

**Comment by davisjr** [comment]
Looks like you don’t have the ConversationID field setup correctly. Make sure the field exists and it’s getting updated with a value when bugs are created. You should see messages in the logs as well if the update failed.

**Comment by mocdaniel** [comment]
I set up the field correctly, I can display the conversation IDs as a column on the work item overview page. Duped entries contain the same conversation ID. As mentioned before, the problem seems to be tracking existing conversation IDs over several runtimes of the service, appending messages to the right conversation ID within the same runtime works just fine.
