### ISSUE TITLE
support for Azure DevOps server

### ISSUE THREAD

**Issue by himzee** [microsoft/mail2bug#114]
Does this utility support AzureDevopsServer?

**Comment by davisjr** [comment]
Yes, although some issues were reported with Azure DevOps Server 2020 specifically. See #112.

**Comment by davisjr** [comment]
Closing this issue. Feel free to open another issue if there is a an issue with setting it up for ADO Server, or you can start a [discussion](https://github.com/microsoft/mail2bug/discussions) if you need general help with configuring stuff.
