### ISSUE TITLE
Please add instructions how to get required OAuth properties to connect to VSO

### ISSUE THREAD

**Issue by sinapis** [Microsoft/mail2bug#16]
Hello Hershi,

I'm trying to set up mail2bug against my VSO account but I'm having difficulties understanding what are the proper values for these fields:

```
<OAuthContext></OAuthContext> 
<OAuthResourceId></OAuthResourceId>
<OAuthClientId></OAuthClientId>
```

Any chance you can provide more details how to obtain this info for my VSO? Maybe an example?

Thanks,
Amir from Sinapis

**Comment by hershi** [comment]
There are details in the fully annotated config, including a link to a relevant site:
