### ISSUE TITLE
No support for alias email addresses on an Exchange mailbox?

### ISSUE THREAD

**Issue by ericvb** [Microsoft/mail2bug#17]
The current implementation doesn't support one exchange email box with different email aliases. (the aliases are then used in different instance configs to differentiate between for example bug mail or a requirement mail : for example bugs.tfs@YourCompany.com and requirements.tfs@YourCompany.com)

The EWS web API will automatically translate the mail alias to the primary email owner of the email box. So when entering de mail2bug code, we know only the primary email address.
The same happens for the acknowledge reply email, it will always be sent from the primary email address.

For the first problem we can use the Transport Message Headers to detect ourselves the email alias used. See http://social.technet.microsoft.com/Forums/en-au/exchangesvrdevelopment/thread/1e5bbde0-218e-466e-afcc-cb60bc2ba692

For the second problem the standard EWS reply should not be used (EmailMessage Reply method).
I changed the code to use the standard NET SmtpClient code to send an email.
(That incorporates the use of the !!!bug #xxxx keyword in the reply html, because smtp don't use the 'conversation' model of Exchange!)

If requested, I can send the changed code as pull request.

Regards,

**Comment by hershi** [comment]
Would be happy to take a PR for the first issue, though
For the second, I'm not sure replying outside of the conversation model is a good idea, since it would break the threading when displaying the messages
