### ISSUE TITLE
Adapt regular expression for appending mails to existing work items

### ISSUE THREAD

**Issue by ericvb** [Microsoft/mail2bug#21]
In the configuration file we find:
`.*(bug|work item)\s*#*\s*(?&lt;id&gt;\d+)`
`!!!(bug|work item)\s*#*\s*(?&lt;id&gt;\d+)`

This regular expression will give a problem if user uses the keyword 'bug' and a digit.
In my case users where testing the module and one had sent an email with the subject: "Test for bug 1"
Result, his mail was appended to the work item 1.
Better we should use the convention like used in Bugzilla: if prefix '#' then it will be interpreted as keyword. Example : 'bug #1' --> this means really append to work item 1

Change regular expression to:
`.*(bug|work item)\s*#\s*(?&lt;id&gt;\d+)`
`!!!(bug|work item)\s*#\s*(?&lt;id&gt;\d+)`

Just an idea to improve the usability...

**Comment by hershi** [comment]
Thanks for the feedback. I didn't know about the Bugzilla convention for this, but it makes sense to align the default config with that.
I'll make the change as soon as I have some time (it's very minor, but I'm not on my development machine at the moment). Feel free to send it as a pull request if you want/need it earlier than that.

**Comment by hershi** [comment]
Fixed
