### ISSUE TITLE
Html email loses his formatting

### ISSUE THREAD

**Issue by ericvb** [Microsoft/mail2bug#22]
Hi,
You can use the ##RawMessageBody tag in the configuration file to put the the html aware mailbody into the tfs item.

But this is not working flawless because of following code in TFSWorkItemManager:
```
                if (field.FieldDefinition.FieldType == FieldType.Html)
                {
                    value = value.Replace("\n", "<br>");
                }
```
Replace this code by
```
                if (field.FieldDefinition.FieldType == FieldType.Html
                    && !value.StartsWith("<html"))  // don't replace \n in a value with real html content, it must not be interpreted!
                {
                    value = value.Replace("\n", "<br>");
                }
```
If requested, I can do a pull request.

**Comment by hershi** [comment]
Thanks for reporting + suggesting a fix.
This is now available in the latest version
