### ISSUE TITLE
Error: TFS connection attempt failed. Not authorized to access VSO collection: One or more errors -System.IO.FileLoadException

### ISSUE THREAD

**Issue by TavishiKaushik** [Microsoft/mail2bug#32]
ERROR:
You are not authorized to access VSO Collection---> System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

It displayed similar error on the first build. After installing latest version 8.0.3 and re-building the solution, it still displayed the same error in log files but not in the error list. 

What is the key problem here? I even tried accessing VSO with account used-it is accessible. 
Why does it specify the same version error again? 
Please provide a solution for the same issue.

**Comment by gxclarke** [comment]
I had the same problem. Had to manually add the project reference to the assembly in the packages folder (downloaded by nuget).
