### ISSUE TITLE
Can this be updated to work with VS 2015 and TFS 2015 update 3

### ISSUE THREAD

**Issue by patdelaney** [Microsoft/mail2bug#54]
I'm a "hack my way through it" programmer, I have pulled down the source and looking at the references and there are Lots of warning. Has anyone gone through the process of updating it this for VS 2015?

I'll take a stab at it, but I may not be doing it right.

Thanks

Pat

**Comment by jeffwilcox** [comment]
It builds fine in VS 2015 and 2017 last I checked. Make sure you're pulling all the NuGet packages, or maybe share the warnings that concern you?

**Comment by patdelaney** [comment]
Yes I figure out how to add them as nuget and now it works. Thanks

Pat
