### ISSUE TITLE
Preserving formatting in work item

### ISSUE THREAD

**Issue by kristingoodman** [Microsoft/mail2bug#65]
Hi again,

I was wondering if there was a way to preserve formatting from the email so it carries over to the work item associated with it. Any help would be appreciated.

Thanks!

**Comment by hershi** [comment]
Hi @kristingoodman,
That depends on the specific setup you're using.
If your issue tracker is set to support HTML format for the description, then you can use try to use the ##RawMessageBody keyword to put the HTML formatted body instead of the plain-text body

**Comment by kristingoodman** [comment]
Yes, that was the fix. Thanks for your help!
