### ISSUE TITLE
Does M2B support Key value pairs?

### ISSUE THREAD

**Issue by patdelaney** [Microsoft/mail2bug#67]
I'm trying to use M2B as a gateway to get issues that were pushed to ServiceNow into TFS. We use SN as our ticketing system. If I have a user that opens a ticket in SN and it's determined to be a bug in one of our applications I want to trigger and email from SN to TFS, and in that Email supply the data needed to open a Bug in TFS.

I see that we can do the basic stuff, The subject of the email is the "Title" of the bug, the message body can get stuffed into Repro Steps.  But lets say that there is other data I want to populate into TFS, I want to know who reported it, the person that reported it may not be the sender... is there a way to do the following:

in the config file define Mnenonic="Symptom" Field="Symptom" Value="@@@Symptom"

Then in the body of the message of the if the users puts:
@@@Symptom: "This only happens the first time the application runs"
the M2B would take that string and put it on the Symptom filed?

Pat

**Comment by davisjr** [comment]
You can include key valye pairs without making any config changes. These overrides look like - 

###Key: Value

Please check the readme on the repo home for basic usage and setup instructions. There's also a fully annotated config file sample under setup instructions that should get you going.
