### ISSUE TITLE
Mail2Bug Bing instance (question for Guy Hershenbaum)

### ISSUE THREAD

**Issue by ohadschn** [Microsoft/mail2bug#92]
Hi @hershi 

Wasn't sure how else to contact you, but I'd love your help with the Bing Mail2Bug system you set up.
Please contact me at my @microsoft.com address (my alias is **_ohads_**).
Of course, feel free to close (or even delete) this issue.

Thanks,
Ohad

**Comment by hershi** [comment]
Hi @ohadschn ,
When I left MS I've left a few people in charge of running the internal instance of Mail2Bug. Have you tried contacting them? Do you need any help beyond that?

I'll reach out via email as well, but replying here just in case

**Comment by ohadschn** [comment]
Thanks Guy! Will reply via e-mail :)
